name: Feature Request
description: Feture something to be in the mod
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the base game?
    validations:
      required: true
